name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test

      - name: Run linters
        run: make lint
